/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pi_Gui;

import Pi_entities.Offre;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author dell
 */
public class ajouterOffre extends javax.swing.JFrame {

    /**
     * Creates new form ajouterOffre
     */
    public ajouterOffre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        imagee = new javax.swing.JTextField();
        parcourir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Ajouter Offres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 30, 160, 18);

        jLabel2.setText("Nom offre :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 55, 14);

        jLabel4.setText("Description :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 60, 14);

        jLabel5.setText("Hebergement :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 270, 72, 14);

        jLabel7.setText("Type Offre :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 340, 60, 14);

        jButton1.setText("suivant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 440, 67, 23);

        jButton2.setText("retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 440, 63, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Destination");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 330, 79, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Programme");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(260, 330, 79, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Itinéraire");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(400, 330, 69, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 80, 180, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 270, 180, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 150, 280, 96);

        jLabel9.setText("inserer votre image :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 90, 110, 30);

        imagee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageeActionPerformed(evt);
            }
        });
        getContentPane().add(imagee);
        imagee.setBounds(440, 80, 130, 30);

        parcourir.setText("parcourir");
        parcourir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcourirMouseClicked(evt);
            }
        });
        parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcourirActionPerformed(evt);
            }
        });
        getContentPane().add(parcourir);
        parcourir.setBounds(580, 80, 80, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-706)/2, (screenSize.height-528)/2, 706, 528);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

      
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        

     
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
//        AjouterItineraire ai =new AjouterItineraire();
//        ai.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Offre of=new Offre();
        of.setNomOffre(jTextField1.getText());
        of.setDescription(jTextArea1.getText());
        of.setHebergement(jTextField4.getText());
      of.setImage(imagee.getText());
        if(jRadioButton3.isSelected()){
            of.setTypeOffre("itinéraire");
         AjouterItineraire a5 = new  AjouterItineraire();
       a5.setVisible(true);
        dispose();
        }
            if(jRadioButton2.isSelected()){
            of.setTypeOffre("programme");
         AjouterProgramme a5 = new  AjouterProgramme();
       a5.setVisible(true);
        dispose();
        }
                if(jRadioButton1.isSelected()){
            of.setTypeOffre("destination");
         AjouterDestination a5 = new  AjouterDestination();
       a5.setVisible(true);
        dispose();
        }
       
                ajouterOffre ao = new ajouterOffre();
                 ao.setVisible(true);
        
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imageeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageeActionPerformed

    private void parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcourirActionPerformed
      
    }//GEN-LAST:event_parcourirActionPerformed

    private void parcourirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcourirMouseClicked
                JFileChooser fc =new JFileChooser(); 
  fc.showOpenDialog(this);
  File file=fc.getSelectedFile();
  if (file !=null)
  {
       imagee.setText(file.getPath());         // TODO add your handling code here:
    } 
    }//GEN-LAST:event_parcourirMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           InterfaceClient a1= new  InterfaceClient() ;
     a1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterOffre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField imagee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton parcourir;
    // End of variables declaration//GEN-END:variables
}
