/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pi_Gui;

import wshop.mail.MailJframe;



/**
 *
 * @author moka
 */
public class homeadmin extends javax.swing.JFrame   {

    /**
     * Creates new form homeadmin
     */
    public homeadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jFchosser = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMexit = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMajouter = new javax.swing.JMenu();
        jMmodifier = new javax.swing.JMenu();
        jMsupprimer = new javax.swing.JMenu();
        jMconsulter = new javax.swing.JMenu();
        jMenuCons = new javax.swing.JMenu();
        jMenuSupp = new javax.swing.JMenu();
        jMsupprimerclient = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1883, 535, -1, -1));

        jFchosser.setBounds(0, 0, 606, 397);
        jDesktopPane1.add(jFchosser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1883, 523, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/bkg-3_1.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 480));

        jLabel1.setText("choisir type offre :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 650, 270));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));

        jMenu1.setText("home");

        jMexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/Exit Icon.jpg"))); // NOI18N
        jMexit.setText("exit");
        jMexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMexitMouseClicked(evt);
            }
        });
        jMenu1.add(jMexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("gestion des comptes responsables");

        jMajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/add.png"))); // NOI18N
        jMajouter.setText("ajouter");
        jMajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMajouterMouseClicked(evt);
            }
        });
        jMajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMajouterActionPerformed(evt);
            }
        });
        jMenu2.add(jMajouter);

        jMmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/images (2).jpg"))); // NOI18N
        jMmodifier.setText("modifier");
        jMmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMmodifierMouseClicked(evt);
            }
        });
        jMmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmodifierActionPerformed(evt);
            }
        });
        jMenu2.add(jMmodifier);

        jMsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/supprimer.png"))); // NOI18N
        jMsupprimer.setText("supprimer");
        jMsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMsupprimerMouseClicked(evt);
            }
        });
        jMsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsupprimerActionPerformed(evt);
            }
        });
        jMenu2.add(jMsupprimer);

        jMenuBar1.add(jMenu2);

        jMconsulter.setText("Les Offres ");
        jMconsulter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMconsulterMouseClicked(evt);
            }
        });

        jMenuCons.setText("Consulter");
        jMenuCons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConsMouseClicked(evt);
            }
        });
        jMconsulter.add(jMenuCons);

        jMenuSupp.setText("Supprimer");
        jMenuSupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSuppMouseClicked(evt);
            }
        });
        jMconsulter.add(jMenuSupp);

        jMenuBar1.add(jMconsulter);

        jMsupprimerclient.setText("supprimer les comptes");
        jMsupprimerclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMsupprimerclientMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMsupprimerclient);

        jMenu5.setText("Envoyer reclamation");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu4.setText("Les Statiqtiques");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-541)/2, 700, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void jMajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMajouterMouseClicked
      AjouterResponsable a1= new  AjouterResponsable() ;
     a1.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMajouterMouseClicked

    private void jMajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMajouterActionPerformed
  
    }//GEN-LAST:event_jMajouterActionPerformed

    private void jMmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmodifierActionPerformed
    
    }//GEN-LAST:event_jMmodifierActionPerformed

    private void jMsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsupprimerActionPerformed
          
    }//GEN-LAST:event_jMsupprimerActionPerformed

    private void jMmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMmodifierMouseClicked
            ModifierResponsable a2= new ModifierResponsable() ;
     a2.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMmodifierMouseClicked

    private void jMsupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMsupprimerMouseClicked
          SupprimerResponsable a3= new SupprimerResponsable() ;
     a3.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMsupprimerMouseClicked

    private void jMsupprimerclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMsupprimerclientMouseClicked
        SuppressionClient c1=new SuppressionClient() ;
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMsupprimerclientMouseClicked

    private void jMconsulterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMconsulterMouseClicked
     
    }//GEN-LAST:event_jMconsulterMouseClicked

    private void jMexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMexitMouseClicked
         Authentification_admin G=new Authentification_admin();
        G.setVisible(true);
  this.setVisible(false);
   dispose();
    }//GEN-LAST:event_jMexitMouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
MailJframe G=new MailJframe();
        G.setVisible(true);
  this.setVisible(false);
   dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuConsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsMouseClicked
        // TODO add your handling code here:
         ConsulterOffres a5 = new  ConsulterOffres();
       a5.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuConsMouseClicked

    private void jMenuSuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSuppMouseClicked
         SupprimerOffre a6 = new  SupprimerOffre();
       a6.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuSuppMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new homeadmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFchosser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMajouter;
    private javax.swing.JMenu jMconsulter;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCons;
    private javax.swing.JMenu jMenuSupp;
    private javax.swing.JMenu jMexit;
    private javax.swing.JMenu jMmodifier;
    private javax.swing.JMenu jMsupprimer;
    private javax.swing.JMenu jMsupprimerclient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
