/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Voy.esprit.Gui;

import Voy.esprit.Facebook.ConnexionFacebook;
import Voy.esprit.Dao.AdministrateurDAO;
import Voy.esprit.Dao.ClientDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author moka
 */
public class authentification_client extends javax.swing.JFrame {
  static int id=0;
    /**
     * Creates new form authentification_client
     */
    public authentification_client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Idauth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pwd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLconnexionFB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel2.setText("Mot de passe");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jToggleButton1.setText("Login ");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 90, 30));

        jToggleButton2.setText("exit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 30));

        Idauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdauthActionPerformed(evt);
            }
        });
        getContentPane().add(Idauth, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, -1));

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 2, 48)); // NOI18N
        jLabel3.setText("authentification");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 310, -1));
        getContentPane().add(Pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/login-pic.jpg"))); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -50, 250, 410));

        jLconnexionFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/fbConnect-bt.png"))); // NOI18N
        jLconnexionFB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLconnexionFBMouseClicked(evt);
            }
        });
        getContentPane().add(jLconnexionFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 420, 90));

        jButton1.setText("S'inscrire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, -1));

        jLabel6.setText("Voulez-vous s'inscrire ?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/layer8.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 480));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
     ClientDAO client = new ClientDAO(); 
        
       for (int i = 0; i < client.DisplayAllclient().size(); i++)
       { 
           if(client.DisplayAllclient().get(i).getLogin().equals(Idauth.getText()) && client.DisplayAllclient().get(i).getPassword().equals(Pwd.getText())) { 
               System.out.print("ok");
                id=client.DisplayAllClient().get(i).getIdCl(); 
              InterfaceClient c=new InterfaceClient();
               this.setVisible(false);
               c.setVisible(true);
        } else
           if(!client.DisplayAllclient().get(i).getLogin().equals(Idauth.getText()) && !client.DisplayAllclient().get(i).getPassword().equals(Pwd.getText()))
           { 
               
               System.out.print("no");
           JOptionPane.showMessageDialog(this, "Login ou Mot de passe invalid!!!!");
           Idauth.setText("");
           Pwd.setText("");
    }//GEN-LAST:event_jToggleButton1ActionPerformed
       }
    }
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
                start m=new start();
               this.setVisible(false);
               m.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void IdauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdauthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdauthActionPerformed

    private void jLconnexionFBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLconnexionFBMouseClicked
         ConnexionFacebook connexionFacebook = new ConnexionFacebook();
        connexionFacebook.loginFb();
    }//GEN-LAST:event_jLconnexionFBMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       InscriptionClient a2= new InscriptionClient() ;
     a2.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(authentification_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(authentification_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(authentification_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(authentification_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new authentification_client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Idauth;
    private javax.swing.JPasswordField Pwd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLconnexionFB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
