/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Voy.esprit.Gui;

import Voy.esprit.Controllers.OffreController;
import Voy.esprit.Dao.DestinationDAO;
import Voy.esprit.Dao.OffreDAO;
import Voy.esprit.Dao.commentaireDAO;
import Voy.esprit.Dao.noteDAO;
import Voy.esprit.entities.Client;
import Voy.esprit.entities.Destination;
import Voy.esprit.entities.Offre;
import Voy.esprit.entities.commentaire;
import Voy.esprit.entities.note;
import javax.swing.JOptionPane;

/**
 *
 * @author Naoufel
 */
public class ConsulterOffresclient extends javax.swing.JFrame {

    /**
     * Creates new form ConsulterOffres
     */
    public ConsulterOffresclient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConsultNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ConsultDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultDesc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        ConsultVille = new javax.swing.JTextField();
        jBretour = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentaire = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jnote = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jTcommentaire = new javax.swing.JToggleButton();
        consulterimage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new OffreController());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 620, 158));

        jLabel1.setText("Type d'offre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        buttonGroup6.add(jRadioButton1);
        jRadioButton1.setText("Destination");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        buttonGroup6.add(jRadioButton2);
        jRadioButton2.setText("Itinéraire");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        buttonGroup6.add(jRadioButton3);
        jRadioButton3.setText("Programme");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel2.setText("Consulter les Offres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel3.setText("Nom Offre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 52, -1));

        ConsultNom.setEditable(false);
        getContentPane().add(ConsultNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 134, 20));

        jLabel4.setText("Date Offre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        ConsultDate.setEditable(false);
        ConsultDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultDateActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 134, 20));

        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 74, -1));

        ConsultDesc.setColumns(20);
        ConsultDesc.setLineWrap(true);
        ConsultDesc.setRows(5);
        jScrollPane2.setViewportView(ConsultDesc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 299, 110));

        jLabel6.setText("Ville Offre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 52, -1));

        ConsultVille.setEditable(false);
        getContentPane().add(ConsultVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 134, -1));

        jBretour.setText("retour");
        jBretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBretourActionPerformed(evt);
            }
        });
        getContentPane().add(jBretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 100, 30));

        commentaire.setColumns(20);
        commentaire.setRows(5);
        jScrollPane3.setViewportView(commentaire);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 240, 70));

        jLabel8.setText("commentaire ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 80, 20));

        jnote.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jnote.setFocusTraversalPolicyProvider(true);
        jnote.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jnoteStateChanged(evt);
            }
        });
        getContentPane().add(jnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 50, -1));

        jLabel9.setText("note ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jTcommentaire.setText("valider");
        jTcommentaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcommentaireActionPerformed(evt);
            }
        });
        getContentPane().add(jTcommentaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 140, -1));
        getContentPane().add(consulterimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 80, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/bkg-3_1.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
       String X="D";
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new OffreController(X));
        
jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
    }
});
        jScrollPane1.setViewportView(jTable1);        
        
        
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        String X="I";
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new OffreController(X));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
    }
});

        jScrollPane1.setViewportView(jTable1);   
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        String X="P";
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new OffreController(X));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
    }
});

        jScrollPane1.setViewportView(jTable1);   
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
                
        Object a = jTable1.getValueAt(row, 0);
        Object b = jTable1.getValueAt(row, 1);
        Object c = jTable1.getValueAt(row, 2);
        Object d = jTable1.getValueAt(row, 3); 
        Object e = jTable1.getValueAt(row, 4); 
        
           
           
           ConsultNom.setText(""+b);
           ConsultDate.setText(""+c);
           ConsultDesc.setText(""+d);
           ConsultVille.setText(""+e);

    }//GEN-LAST:event_jTable1MouseClicked

    private void ConsultDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultDateActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jBretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBretourActionPerformed
     InterfaceClient  G=new InterfaceClient();
        G.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBretourActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTcommentaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcommentaireActionPerformed
           if (!commentaire.getText().equals(""))
           {
               int x= jTable1.getSelectedRow();
          String y =""+ jTable1.getValueAt(x, 0);
             
         
          commentaire com=new commentaire();
      Offre of =new Offre();
     of.setIdOffre(Integer.parseInt(y));
    Client cl= new   Client(); 
    cl.setIdCl(authentification_client.id);
      
         com.setCommentaire(commentaire.getText());
    com.setFk_IdCl(cl);
    com.setFk_IdOffre(of);
         note not =new note();
          not.setValeurnote(Integer.parseInt(jnote.getValue().toString()));
     not.setFk_IdOffre(of);
     not.setFk_IdCl(cl);
     
         commentaireDAO comDao =new commentaireDAO();
      comDao.insertCommentaire(com);
         noteDAO noteDao =new noteDAO();
       noteDao.insertnote(not);
                
        
           }
           else
           {
            JOptionPane.showMessageDialog(rootPane, "erreur champ commentaitre vide ", null, WIDTH);   
           }
    }//GEN-LAST:event_jTcommentaireActionPerformed

    private void jnoteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jnoteStateChanged
    
    }//GEN-LAST:event_jnoteStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterOffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterOffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterOffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterOffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsulterOffresclient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConsultDate;
    private javax.swing.JTextArea ConsultDesc;
    private javax.swing.JTextField ConsultNom;
    private javax.swing.JTextField ConsultVille;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextArea commentaire;
    private javax.swing.JLabel consulterimage;
    private javax.swing.JButton jBretour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jTcommentaire;
    private javax.swing.JSpinner jnote;
    // End of variables declaration//GEN-END:variables
}
