/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pi_Gui;

/**
 *
 * @author moka
 */
public class homeadmin extends javax.swing.JFrame   {

    /**
     * Creates new form homeadmin
     */
    public homeadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jFchosser = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMsauvgarder = new javax.swing.JMenu();
        jMexit = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMajouter = new javax.swing.JMenu();
        jMmodifier = new javax.swing.JMenu();
        jMsupprimer = new javax.swing.JMenu();
        jMconsulter = new javax.swing.JMenu();
        jMsupprimerclient = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jFchosser.setBounds(0, 0, 606, 397);
        jDesktopPane1.add(jFchosser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("home");

        jMsauvgarder.setText("sauvgarder ");
        jMsauvgarder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMsauvgarderStateChanged(evt);
            }
        });
        jMsauvgarder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMsauvgarderItemStateChanged(evt);
            }
        });
        jMsauvgarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsauvgarderActionPerformed(evt);
            }
        });
        jMenu1.add(jMsauvgarder);

        jMexit.setText("exit");
        jMexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMexitMouseClicked(evt);
            }
        });
        jMenu1.add(jMexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("gestion des comptes responsables");

        jMajouter.setText("ajouter");
        jMajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMajouterMouseClicked(evt);
            }
        });
        jMajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMajouterActionPerformed(evt);
            }
        });
        jMenu2.add(jMajouter);

        jMmodifier.setText("modifier");
        jMmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMmodifierMouseClicked(evt);
            }
        });
        jMmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmodifierActionPerformed(evt);
            }
        });
        jMenu2.add(jMmodifier);

        jMsupprimer.setText("supprimer");
        jMsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMsupprimerMouseClicked(evt);
            }
        });
        jMsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsupprimerActionPerformed(evt);
            }
        });
        jMenu2.add(jMsupprimer);

        jMenuBar1.add(jMenu2);

        jMconsulter.setText("consulter les offres ");
        jMconsulter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMconsulterMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMconsulter);

        jMsupprimerclient.setText("supprimer les comptes");
        jMsupprimerclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMsupprimerclientMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMsupprimerclient);

        jMenu5.setText("Statistiques");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(627, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMajouterMouseClicked
      AjouterResponsable a1= new  AjouterResponsable() ;
     a1.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMajouterMouseClicked

    private void jMajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMajouterActionPerformed
  
    }//GEN-LAST:event_jMajouterActionPerformed

    private void jMmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmodifierActionPerformed
    
    }//GEN-LAST:event_jMmodifierActionPerformed

    private void jMsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsupprimerActionPerformed
          
    }//GEN-LAST:event_jMsupprimerActionPerformed

    private void jMmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMmodifierMouseClicked
            ModifierResponsable a2= new ModifierResponsable() ;
     a2.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMmodifierMouseClicked

    private void jMsupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMsupprimerMouseClicked
          SupprimerResponsable a3= new SupprimerResponsable() ;
     a3.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMsupprimerMouseClicked

    private void jMsupprimerclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMsupprimerclientMouseClicked
       SuppressionClient a4 = new  SuppressionClient();
       a4.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMsupprimerclientMouseClicked

    private void jMconsulterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMconsulterMouseClicked
      ConsulterOffres a5 = new  ConsulterOffres();
       a5.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMconsulterMouseClicked

    private void jMsauvgarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsauvgarderActionPerformed
      
    }//GEN-LAST:event_jMsauvgarderActionPerformed

    private void jMsauvgarderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMsauvgarderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMsauvgarderStateChanged

    private void jMsauvgarderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMsauvgarderItemStateChanged
 
    }//GEN-LAST:event_jMsauvgarderItemStateChanged

    private void jMexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMexitMouseClicked
         Authentification G=new Authentification();
        G.setVisible(true);
  this.setVisible(false);
   dispose();
    }//GEN-LAST:event_jMexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new homeadmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFchosser;
    private javax.swing.JMenu jMajouter;
    private javax.swing.JMenu jMconsulter;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMexit;
    private javax.swing.JMenu jMmodifier;
    private javax.swing.JMenu jMsauvgarder;
    private javax.swing.JMenu jMsupprimer;
    private javax.swing.JMenu jMsupprimerclient;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
