/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pi_Gui;

/**
 *
 * @author moka
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBadmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBclient = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jBresponsable = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Authentification ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, 20));

        jBadmin.setFont(new java.awt.Font("Century Schoolbook", 0, 48)); // NOI18N
        jBadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/vip.png"))); // NOI18N
        jBadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadminActionPerformed(evt);
            }
        });
        getContentPane().add(jBadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Nouveau Client ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 140, 20));

        jBclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/basic.png"))); // NOI18N
        jBclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclientActionPerformed(evt);
            }
        });
        getContentPane().add(jBclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 190, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Nouvelle Agence ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 180, 40));

        jBresponsable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/moderator.png"))); // NOI18N
        getContentPane().add(jBresponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/e2fb491815745fba7fd7b4246252af6726238c5b.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadminActionPerformed
         Authentification G=new Authentification();
        G.setVisible(true);
        this.setVisible(false);    
    }//GEN-LAST:event_jBadminActionPerformed

    private void jBclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclientActionPerformed
         authentification_client G=new authentification_client();
        G.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBclientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBadmin;
    private javax.swing.JToggleButton jBclient;
    private javax.swing.JButton jBresponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
