/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pi_Gui;
import Pi_Controllers.RespAgenceController;
import Pi_Dao.RespDAO;
import Pi_entities.ResponsableAgence;

/**
 *
 * @author Naoufel
 */
public class SupprimerResponsable extends javax.swing.JFrame {

    /**
     * Creates new form SupprimerResponsable
     */
    public SupprimerResponsable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbDelAgAnnul = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DelResAgNam = new javax.swing.JTextField();
        DelfResAgPr = new javax.swing.JTextField();
        JbDelAg = new javax.swing.JButton();
        DelfAgtel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DelfAgAdr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Idrespon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbDelAgAnnul.setText("Annuler");
        JbDelAgAnnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDelAgAnnulActionPerformed(evt);
            }
        });
        getContentPane().add(JbDelAgAnnul, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 251, 96, -1));

        jLabel4.setText("Prenom Responsable Agence");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));

        jLabel3.setText("Nom Responsable Agence");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

        jLabel5.setText("Adresse Agence");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 124, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel1.setText("Supprimer une  Agence");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, 269, -1));

        jLabel6.setText("Telephone Agence");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, -1, -1));

        DelResAgNam.setEditable(false);
        getContentPane().add(DelResAgNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 99, 83, -1));

        DelfResAgPr.setEditable(false);
        getContentPane().add(DelfResAgPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 137, 83, -1));

        JbDelAg.setText("Supprimer");
        JbDelAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDelAgActionPerformed(evt);
            }
        });
        getContentPane().add(JbDelAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 251, -1, -1));

        DelfAgtel.setEditable(false);
        getContentPane().add(DelfAgtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 213, 83, -1));

        jTable1.setModel(new RespAgenceController());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 99, 235, 175));

        DelfAgAdr.setEditable(false);
        getContentPane().add(DelfAgAdr, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 175, 83, -1));

        jLabel2.setText("Id Responsable");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        Idrespon.setEditable(false);
        Idrespon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdresponActionPerformed(evt);
            }
        });
        getContentPane().add(Idrespon, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 68, 83, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PI_Icone/bkg-3_1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbDelAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDelAgActionPerformed
        // TODO add your handling code here:
        ResponsableAgence Resp=new ResponsableAgence();
      int a=Integer.parseInt(Idrespon.getText());
      
         RespDAO respDao =new RespDAO();
      respDao.deletResp(a);
      jTable1 = new javax.swing.JTable();

jTable1.setModel(new RespAgenceController());

jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
    }
});

jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_JbDelAgActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
        Object idrespo = jTable1.getValueAt(row, 0);
        Object a = jTable1.getValueAt(row, 1);
        Object b = jTable1.getValueAt(row, 2);
        Object c = jTable1.getValueAt(row, 3);
        Object d = jTable1.getValueAt(row, 4); 
       
        
        
            
           
           DelResAgNam.setText(""+a);
           DelfResAgPr.setText(""+b);
           DelfAgAdr.setText(""+c);
           DelfAgtel.setText(""+d);
           Idrespon.setText(""+idrespo);
           
           
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void IdresponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdresponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdresponActionPerformed

    private void JbDelAgAnnulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDelAgAnnulActionPerformed
        // TODO add your handling code here:
         homeadmin G=new homeadmin();
        G.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JbDelAgAnnulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupprimerResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupprimerResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupprimerResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupprimerResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SupprimerResponsable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DelResAgNam;
    private javax.swing.JTextField DelfAgAdr;
    private javax.swing.JTextField DelfAgtel;
    private javax.swing.JTextField DelfResAgPr;
    private javax.swing.JTextField Idrespon;
    private javax.swing.JButton JbDelAg;
    private javax.swing.JButton JbDelAgAnnul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
